name: A workflow for my Hello World file
on:
  workflow_dispatch:

jobs:
  build:
    if: github.ref == 'refs/heads/main'
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: echo "Triggered in main branch"
        shell: bash
