name: Running jobs in a matrix
on:
  schedule:
    - cron: "*/5 * * * *"
    
jobs:
  run_per_env:
    strategy:
      matrix:
        environment: ['dev', 'acc', 'prod']
    uses: ./.github/workflows/second.yaml
    with:
      environment: ${{ matrix.environment }}
    
