on:
  schedule:
    - cron: "*/5 * * * *"
    
jobs:
  run_per_env:
    strategy:
      matrix:
        environment: ['dev', 'acc', 'prod']
    runs-on: ubuntu-latest
    environment: ${{ matrix.environment }}
    
    steps:
      - name: Running matrix jobs per environment
        run: echo "Running in ${{ matrix.environment }}"
