name: "Second workflow"

on:
  workflow_call:
    inputs: 
      environment:
        type: string
        required: true
jobs:
  second-workflow:
    name: "Second Workflow Steps"
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Download workspace
        uses: actions/download-artifact@master
        with:
          name: sample-workspace
          path: ${{ github.workspace }}
          
      - name: Print workspace contents
        run: ls -ltra
          
