name: "Second workflow"

on:
  workflow_dispatch:
    
jobs:
  second-workflow:
    name: "Second Workflow Steps"
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Download first workspace
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: main.yml
          name: sample-workspace
          path: ${{ github.workspace }}
      - name: Print workspace contents
        run: ls -ltr
          
