name: "Second workflow"

on:
  workflow_dispatch:
    inputs: 
      environment:
        type: string
        required: true
jobs:
  second-workflow:
    name: "Second Workflow Steps"
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Download first workspace
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: main.yml
          name: sample-workspace
          path: ${{ github.workspace }}
      - name: Print workspace contents
        run: |
          ls -ltr
          echo ${{github.event.inputs.environment}}
          echo ${{inputs.environment}}
          
