name: "Deploy Selectively"

on:
  workflow_call:
    inputs:
      deploy_stacks:
        type: string
        required: true
jobs:
  job1:
    name: Deploy 1
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
  steps:  
    - name: Running Job1
      if: ${{ fromJson(inputs.deploy_stacks)..deploy_all || fromJson(inputs.deploy_stacks).deploy_1 }}
      run: |
        echo inputs.deploy_stacks
        echo fromJson(inputs.deploy_stacks).deploy_1
        echo "Job1 Triggered"
        
  job2:
    name: "Run Job2"
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    
    steps:
      - name: Running Job2
        if: ${{ fromJson(inputs.deploy_stacks).deploy_all || fromJson(inputs.deploy_stacks).deploy_2 }}
        run: echo "Job2 Triggered"
        
  job3:
    name: "Run Job3"
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    
    steps:
      - name: Running Job3
        if: ${{ fromJson(inputs.deploy_stacks).deploy_all || fromJson(inputs.deploy_stacks).deploy_3 }}
        run: echo "Job3 Triggered"
      
