name: "Deploy Selectively"

on:
  workflow_call:
    inputs:
      deploy_stacks:
        type: string
        required: true
jobs:
  job1:
    name: Deploy 1
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:  
      - name: Running Job1
        id: step1
        if: |
          fromJson(inputs.deploy_stacks).deploy_1 == true || 
          fromJson(inputs.deploy_stacks).deploy_all == true
        run: |
          echo ${{fromJson(inputs.deploy_stacks).deploy_1}}
          echo "Job1 Triggered"
      - name: Continue to step2
        if: ${{steps.step1.conclusion != 'skipped'}}
        run: echo "Running step 2"
        
  job2:
    name: Deploy 2
    runs-on: ubuntu-latest
    needs: job1
    permissions:
      id-token: write
      contents: read
    
    steps:
      - name: Running Job2
        if: |
          fromJson(inputs.deploy_stacks).deploy_2 == true || 
          fromJson(inputs.deploy_stacks).deploy_all == true
        run: |
          echo ${{fromJson(inputs.deploy_stacks).deploy_2}}
          echo "Job2 Triggered"
        
  job3:
    name: Deploy 3
    runs-on: ubuntu-latest
    needs: job2
    permissions:
      id-token: write
      contents: read
    
    steps:
      - name: Running Job3
        if: |
          fromJson(inputs.deploy_stacks).deploy_3 == true || 
          fromJson(inputs.deploy_stacks).deploy_all == true
        run: |
          echo ${{fromJson(inputs.deploy_stacks).deploy_3}}
          echo "Job3 Triggered"
          
  workflow_summary:
    name: Add Workflow Summary
    runs-on: ubuntu-latest
    needs: job3
    permissions:
      id-token: write
      contents: read
    
    steps:
      - name: Adding markdown
        run: |
          echo 'Stacks deployed in this run: :rocket:' >> $GITHUB_STEP_SUMMARY
          stacks=$(echo ${{toJson(inputs.deploy_stacks)}} | jq -r '.[] | select(.* == true) | .key')
          echo "$stacks" >> $GITHUB_STEP_SUMMARY
      
