name: Accept User Input in running workflow
on:
  workflow_dispatch:
  
jobs:
  run-interactive-shell:
    name: Run interactive shell
    runs-on: ubunutu-latest
    
    steps:
      - name: Execute Shell
        run: |
          echo "Hello User, Provide your details below:"
          read -p 'username:' user
          read -sp 'password:' pass
          echo "Thanks $user for providing the above details"
    
  
