name: Selective Deploy
on:
  workflow_dispatch:
    inputs:
      Deploy_All:
        type: boolean
      Deploy_1:
        type: boolean
      Deploy_2:
        type: boolean
      Deploy_3:
        type: boolean
      Deploy_4:
        type: boolean
      Deploy_5:
        type: boolean  
  
jobs:
  job1:
    uses: /.github/workflows/shared-workflow.yml
    with:
      deploy_stacks: |
        {
          "deploy_all": "${{github.event.inputs.Deploy_All}}",
          "deploy_shared_infra": "${{github.event.inputs.Deploy_1}}",
          "deploy_eks_infra": "${{github.event.inputs.Deploy_2}}",
          "deploy_eks_data": "${{github.event.inputs.Deploy_3}}",
          "deploy_common_data": "${{github.event.inputs.Deploy_4}}",
          "deploy_core_apis": "${{github.event.inputs.Deploy_5}}"
        }  
  
