name: Test user Inputs
on:
  workflow_dispatch:
    inputs:
      Deploy-List:
        type: string
        required: true
        description: 'Please use one or more of the following values as a comma separated list: Deploy_All,Deploy_1,Deploy_2,Deploy_3,Deploy_4'
env: 
  DEPLOY_LIST: ${{ github.event.inputs.Deploy-List }}
jobs:
  deploy-stack:
    name: "OSDU DP Deploy Infra"
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    
    steps:
      - name: Input Validation
        run: |
          DEPLOY_COUNT=$(echo -n $DEPLOY_LIST | grep -Fo 'Deploy' | wc -l)
          echo $DEPLOY_COUNT
          if [[ $DEPLOY_COUNT > 1 ]]; then
            COMMA_COUNT=$(echo -n $DEPLOY_LIST | grep -Fo ',' | wc -l)
            echo $COMMA_COUNT
            if [[ $COMMA_COUNT != $DEPLOY_COUNT-1 ]]; then
              echo "Please input all values separated by commas"
              exit 1
            fi
          fi
        shell: bash
      - name: Deploy 1
        if: contains(env.DEPLOY_LIST, 'Deploy-1') || contains(env.DEPLOY_LIST, 'Deploy-All')
        run: |
          echo ${{ env.DEPLOY_LIST }}
          echo "Deploy 1 executing"
      - name: Deploy 2
        if: ${{ github.event.inputs.Deploy-2 == 'true' }}
        run: |
          echo "Deploy 2 executing"
      - name: Deploy 3
        if: ${{ github.event.inputs.Deploy-3 == 'true' }}
        run: |
          echo "Deploy 3 executing"
      - name: Deploy 4
        if: ${{ github.event.inputs.Deploy-4 == 'true' }}
        run: |
          echo "Deploy 4 executing"
  
