name: Test user Inputs
on:
  workflow_dispatch:
    inputs:
      Deploy-List:
        type: string
        required: true
        description: "Please use one or more of the following values as a comma separated list.\nDeploy-All,Deploy-1,Deploy-2,Deploy-3,Deploy-4"
jobs:
  deploy-stack:
    name: "OSDU DP Deploy Infra"
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Deploy 1
        if: ${{ github.event.inputs.Deploy-1 == 'true' }}
        run: |
          echo "Deploy 1 executing"
      - name: Deploy 2
        if: ${{ github.event.inputs.Deploy-2 == 'true' }}
        run: |
          echo "Deploy 2 executing"
      - name: Deploy 3
        if: ${{ github.event.inputs.Deploy-3 == 'true' }}
        run: |
          echo "Deploy 3 executing"
      - name: Deploy 4
        if: ${{ github.event.inputs.Deploy-4 == 'true' }}
        run: |
          echo "Deploy 4 executing"
  
