name: Env Variable Passing
on:
  workflow_dispatch:
    
jobs:
  set-env:
    name: "Set Env Variable"
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    
    steps:
      - name: Set env variable
        run: |
          echo "MYVAR=Success" >> $GITHUB_ENV
      - name: Print env variable
        run: echo $MYVAR
        
  get-env:
    name: "Get Env Variable"
    runs-on: ubuntu-latest
    needs: set-env
    permissions:
      id-token: write
      contents: read
    
    steps:
      - name: Get env variable
        run: echo $MYVAR
      
  
