name: Env Variable Passing
on:
  workflow_dispatch:
env:
  MYVAR: pass
  
jobs:
  set-env:
    name: "Set Env Variable"
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    
    steps:
      - name: Fail the Job
        run: exit 1
        
      - name: Set env variable
        if: always()
        run: |
          echo "MYVAR=fail" >> $GITHUB_ENV
          
      - name: Print env variable
        run: echo $MYVAR
        
  get-env:
    name: "Get Env Variable"
    runs-on: ubuntu-latest
    needs: set-env
    if: always()
    permissions:
      id-token: write
      contents: read
    
    steps:
      - name: Get env variable
        run: echo ${{ env.MYVAR }}
      
  
