name: Env Variable Passing
on:
  workflow_dispatch:
    inputs:
      workflow:
        type: choice
        options:
          - pass
          - fail
  
jobs:
  job1:
    name: "Run Job1"
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    
    steps:
      - name: Conditionally fail the Job
        run: |
          if [[ ${{github.event.inputs.workflow}} == 'fail' ]]; then
            exit 1
          fi
        
      - uses: actions/github-script@v2
        id: check
        if: failure()
        with:
          script: |
            const { owner, repo } = context.repo
              console.log('Cancelling ...');
              const run_id = "${{ github.run_id }}";
              await github.actions.cancelWorkflowRun({ owner, repo, run_id });
          
      - name: Running Job1
        run: echo "Job1 Triggered"
        
  job2:
    name: "Run Job2"
    runs-on: ubuntu-latest
    needs: job1
    if: |
      always() &&
      (needs.job1.result == 'success' || needs.job1.result == 'skipped')
    permissions:
      id-token: write
      contents: read
    
    steps:
      - name: Running Job2
        run: echo "Job2 Triggered"
        
  job3:
    name: "Run Job3"
    runs-on: ubuntu-latest
    needs: job2
    if: |
      always() &&
      (needs.job2.result == 'success' || needs.job2.result == 'skipped')
    permissions:
      id-token: write
      contents: read
    
    steps:
      - name: Running Job3
        run: echo "Job3 Triggered"
      
  
